spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEMO_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${DEMO_POSTGRESQL_USERNAME:root}
    password: ${DEMO_POSTGRESQL_PASSWORD:root}

    # connection pool (usage: hikari pool)
    hikari:
      connection-timeout: 30000  # 30초
      idle-timeout: 600000      # 10분
      max-lifetime: 1800000     # 30분
      maximum-pool-size: 10     # 300은 너무 큽니다. 일반적인 웹 애플리케이션의 경우 10-20 정도면 충분
      minimum-idle: 5
      leak-detection-threshold: 30000  # 30초로 증가
      auto-commit: true
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # profile 설정 안 해도 확인할 수 있도록 임시로 true 함.
    hibernate:
      ddl-auto: none # flyway 사용하면 none 또는 validate (엄격한 경우 validate)

  flyway:
    baseline-on-migrate: true # flyway schema history 테이블이 없다면 생성한다.
    locations:
      - classpath:db/migration/v1_0
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  
jwt:
  secret: dptmvkzkflsktkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  
file:
  dir: C:/upload/
